mod_version = 2.0.1
mod_name = All Items Server
mod_id = allitems73
mod_authors = Bowser_The_Boss
mod_licence = All Rights Reserved
mod_group_id = xyz.quazaros
mod_description=Keep track of all the items everyone has collected